#!/usr/bin/env node
const getTime = (hours) => {
  if (hours >= 3 && hours <= 10) return 'morning';
  else if (hours >= 11 && hours <= 15) return 'afternoon';
  else if (hours >= 16 && hours <= 18) return 'evening';
  else return 'night';
};

const hours = new Date().getHours();
const time = getTime(hours);

console.log(`Good ${time}, Taufik!`);
